language: java

# Set JDK needed for JavaTestApplication
jdk:
  - oraclejdk8    
  
 # Enable initializing of GUI context required for running tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: 
 - wget https://github.com/codenameone/cn1-binaries/archive/master.zip
 - unzip master.zip -d ../
 - mv ../cn1-binaries-master ../cn1-binaries
 - rm master.zip
 - wget https://github.com/codenameone/codenameone-skins/archive/master.zip
 - unzip master.zip -d ../
 - mv ../codenameone-skins-master ../codenameone-skins
 - cd ../codenameone-skins
 - ./build_skins.sh
 - mv ../CodenameOne ../cn1
 - cd ../cn1
 - cd CodenameOne
 - ant jar
 - cd ../CodenameOneDesigner
 - mkdir dist
 - mkdir dist/lib
 - ant release
